### ISSUE TITLE
CI/CD pipeline for build and test

### ISSUE THREAD

**Issue by bizzbyster** [Project-Faster/qpep#10]
It would be great if this project could start building versioned releases that would include pre-built binaries and an installer.

**Comment by parvit** [comment]
Maybe we could connect one of your aws machines with the github actions?

**Comment by bizzbyster** [comment]
- this should be implemented as Infrastructure as Code so that resources (VMs, etc) are not simply running all the time. They are created and destroyed as part of the automated release process, etc.

**Comment by parvit** [comment]
@bizzbyster @mfoxworthy 
Do we have a VM platform available for the machines deploy?

**Comment by parvit** [comment]
Two workflows are available now:
* AutoBuild: Will build automatically when pushing to "main" or a "testing-" branch, when triggered manually it will also produce the 32 bits version
* Release: Builds the entire package for all platforms and generates a new release with the produced artifacts, also creates the associated git tags (Only manual trigger)

**Comment by parvit** [comment]
Built automatically on commit https://github.com/Project-Faster/qpep/pull/36/commits/6924592cd69400fffafe42011d6001ee48daa08a.
