### ISSUE TITLE
Error when closing client or stopping client

### ISSUE THREAD

**Issue by mfoxworthy** [Project-Faster/qpep#14]
Whenever I use the quit menu item or the Client Enabled menu item when the client is active, I get an error window. It says it cannot quit the client and asks to force terminate.

![Screen Shot 2022-08-05 at 1 16 21 PM](https://user-images.githubusercontent.com/8184748/183156508-788143af-fe51-4c24-861a-b52da3e84035.png)

**Comment by parvit** [comment]
@mfoxworthy Version at https://github.com/Project-Faster/qpep/tree/issue-14 changes the behavior to auto-termination in case the client is unresponsive.

Please test it and send feedback.

**Comment by mfoxworthy** [comment]
> @mfoxworthy Version at https://github.com/Project-Faster/qpep/tree/issue-14 changes the behavior to auto-termination in case the client (or server) is unresponsive.
> 
> Please test it and send feedback.

I will test today.
