### ISSUE TITLE
QPEP and VPN do not work when both are enabled - MUST HAVE

### ISSUE THREAD

**Issue by mfoxworthy** [Project-Faster/qpep#17]
When I start the VPN and then start qpep, I can't send or receive any data. They do work independently. I am using Cisco AnyConnect. I have not tried any others but looking at VpnHood should show us how to make WinDivert work with qpep and VPNs.

https://github.com/vpnhood/VpnHood

I'd like to get the other minor issues resolved before we tackle this one.

**Comment by parvit** [comment]
With this change i believe it is possible now to use VPNs in conjunction with QPEP.

The change involves a basic principle, which is that qpep while it still redirects every
packet in the system (bar loopback), it will now _reinject unchanged_ the ones that do 
not belong to interfaces that handle the default route (0.0.0.0).

Independent setup
------

In this setup:
* QPep listens on address of default local gateway 
* QPep points to gateway _not_ in the VPN

In this case all packets from the VPN interface are captured and transparently reinjected, 
they can continue their route as if never intercepted and also the QPep redirection 
continues to work undisturbed.
It does not allow the traffic _of_ the vpn to be accelerated, nor the local addresses 
_accelerated_ traffic be routed _through_ the vpn.
The advantage of this mode is that it works nearly completely automatically as the interfaces are discovered by the client autonomously.

Combined setup
------
If the VPN does have the ability to push the default gateway to the client when connected (also manual setup could be arranged probably), than it is possible to route _accelerated_ traffic _through_ the VPN.
The limitation is that the _listening_ and _gateway_ for QPep are to be set to addresses inside the VPN and have to be set manually in the configuration.

Configurations tested
------
VPN used: OpenVPN 2.5.7.0 + Windows GUI 11.29.0.0
setup: Comnbined and Independent, UDP and TCP TUN / TAP, UDP/TCP TAP with push of default gateway server-side -> client-side
Attached to the post the configurations and certificates used
[openvpn_configs.zip](https://github.com/Project-Faster/qpep/files/9530943/openvpn_configs.zip)

Please test and give feedback.

**Comment by bizzbyster** [comment]
@mfoxworthy @parvit is this working? Should I expect it to work with my Cisco VPN? Let me know if you want me to try it out.

**Comment by parvit** [comment]
hi unfortunately it does not work on cisco at the moment, i'll send you a
private message with the details.

Il Ven 18 Nov 2022, 19:52 bizzbyster ***@***.***> ha scritto:

**Comment by bizzbyster** [comment]
ok thanks
