### ISSUE TITLE
Simple bandwidth activity meter in the UI

### ISSUE THREAD

**Issue by bizzbyster** [Project-Faster/qpep#3]
Goal: present the user with some high level data to convince them that the QPEP client is actually working
- instantaneous goodput (not including QUIC/TCP header data) in the upload and download directions. Show this activity in time series graph covering the last 5 minutes. Something along these lines:
![image](https://user-images.githubusercontent.com/4001792/179048796-862a2e10-09d8-4d4c-b883-dce9978c2989.png)

**Comment by parvit** [comment]
The GUI part is going to take some research time to see how best to implement.

In the mean time, do you have any additional statistics you would like to collect?

**Comment by parvit** [comment]
@bizzbyster 
[qpep_interface.pdf](https://github.com/Project-Faster/qpep/files/9186852/qpep_interface.pdf)
Here's my proposal for the change, let me know if you have any question for this.

I estimate a 2 week effort at minimum.

**Comment by bizzbyster** [comment]
@parvit What javascript framework are you using for this? The functionality looks great to me but the aesthetics might be improved. Maybe you check this in as designed and then @nachocardozop we can ask another engineer like @avnerjose to update the look and feel?

**Comment by parvit** [comment]
Hi i'm sorry for the confusion but that is just a functional mockup i did
not intend for it to be the final look.

I was thinking of using a material theme an the Aurelia framework for the
actual js.

If you do not have functional objections i will begin working on it.

Il giorno mer 27 lug 2022 alle ore 16:34 bizzbyster <
***@***.***> ha scritto:

**Comment by bizzbyster** [comment]
Sounds good if @mfoxworthy is good with the functionality.

**Comment by mfoxworthy** [comment]
> Sounds good if @mfoxworthy is good with the functionality.

Functionality is perfect. There is no question whether the PEP is working or not. That is the main goal.

**Comment by parvit** [comment]
I can start already, however to complete it i'll require the list of statistics/performance counters that should be collected.

**Comment by parvit** [comment]
After today's meeting it was confirmed that the following statistics are required to be collected for clients:
* Current number of connections
* Current Download speed
* Current Upload speed
* Total number of bytes received
* Total number of bytes sent

**Comment by parvit** [comment]
Hello everyone, the development is completed in the branch https://github.com/Project-Faster/qpep/tree/status-gui 

Additions in this branch are:
* Webgui implementation (with Aurelia framework)
* Local API Server
* Performance counters
* Version tracking
* Webgui tray integration

With respect to the initial proposal the only thing missing is the opening of the webgui with a double click on the tray icon, it is not actually supported by the library at the moment.
However if we decide to move forward with #13 than we can insert that change too.

**Comment by parvit** [comment]
Hi everyone, any feedback for this? @mfoxworthy @bizzbyster

**Comment by bizzbyster** [comment]
I will be taking a look today-- sorry for my slowness. I believe Mike has been testing it so I'm sure we'll get his review comments soon.

**Comment by parvit** [comment]
Feature tested positively and merged.
