### ISSUE TITLE
Bug: Diverter messages will be ignored

### ISSUE THREAD

**Issue by bizzbyster** [Project-Faster/qpep#7]
This message shows up in my log file on the qpep client. What does it mean?

Could it be related to this:

The readme says:
![image](https://user-images.githubusercontent.com/4001792/182707001-30d2c31a-dd2f-46c6-985a-f2b4d19284a1.png)

But there is no WinDivert.sys in the windivert\x64 directory. Only WinDivert64.sys.
 
Am I missing a .sys file? Or, is the readme wrong?

**Comment by parvit** [comment]
the readme was updated as you said in the mail.

the message is unrelated.
