### ISSUE TITLE
Remove requirement to "run as Administrator"

### ISSUE THREAD

**Issue by bizzbyster** [Project-Faster/qpep#8]
Currently qpep-tray.exe has to be "run as administrator" according to the readme. Can we remove this requirement by using a windows service?

**Comment by parvit** [comment]
it is possible but It would require a lot of rework of the tray icon and the client.

I'll begin working on it for after i've completed  the web ststus gui.

**Comment by parvit** [comment]
This development is done, we can start testing as soon as testing on #21 is done.

**Comment by bizzbyster** [comment]
AWESOME!

**Comment by parvit** [comment]
Testing yesterday by @mfoxworthy confirmed that the feature is working as intended.
